struct {
	enum channel_state v;
	const char *name;
} enum_channel_state_names[] = {
	{ CHANNELD_AWAITING_LOCKIN, "CHANNELD_AWAITING_LOCKIN" },
	{ CHANNELD_NORMAL, "CHANNELD_NORMAL" },
	{ CHANNELD_SHUTTING_DOWN, "CHANNELD_SHUTTING_DOWN" },
	{ CLOSINGD_SIGEXCHANGE, "CLOSINGD_SIGEXCHANGE" },
	{ CLOSINGD_COMPLETE, "CLOSINGD_COMPLETE" },
	{ AWAITING_UNILATERAL, "AWAITING_UNILATERAL" },
	{ FUNDING_SPEND_SEEN, "FUNDING_SPEND_SEEN" },
	{ ONCHAIN, "ONCHAIN" },
	{ CLOSED, "CLOSED" },
	{ DUALOPEND_OPEN_INIT, "DUALOPEND_OPEN_INIT" },
	{ DUALOPEND_AWAITING_LOCKIN, "DUALOPEND_AWAITING_LOCKIN" },
	{ 0, NULL } };
struct {
	enum state_change v;
	const char *name;
} enum_state_change_names[] = {
	{ REASON_UNKNOWN, "REASON_UNKNOWN" },
	{ REASON_LOCAL, "REASON_LOCAL" },
	{ REASON_USER, "REASON_USER" },
	{ REASON_REMOTE, "REASON_REMOTE" },
	{ REASON_PROTOCOL, "REASON_PROTOCOL" },
	{ REASON_ONCHAIN, "REASON_ONCHAIN" },
	{ 0, NULL } };
